# Generated by Django 3.2.15 on 2024-04-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20240409_2119'),
    ]

    def calculate_prices(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        old_orderitems = OrderItem.objects.update_or_create()

    operations = [
            migrations.RunPython(calculate_prices),
    ]
